INSERT IGNORE INTO category (category_name, sub_category, sla_time_hours, is_visible, department_id) VALUES 
-- Cloud / DevOps (ID 1)
('Cloud / DevOps', 'Auto Scaling Failure', 6, true, 1),
('Cloud / DevOps', 'Backup Restore Failure', 12, true, 1),
('Cloud / DevOps', 'CI/CD Pipeline Failure', 6, true, 1),
('Cloud / DevOps', 'Cloud Cost Anomaly', 24, true, 1),
('Cloud / DevOps', 'Cloud Service Outage', 2, true, 1),
('Cloud / DevOps', 'Configuration Drift', 12, true, 1),
('Cloud / DevOps', 'Container Crash', 4, true, 1),
('Cloud / DevOps', 'Deployment Failure', 6, true, 1),
('Cloud / DevOps', 'Image Vulnerability Detected', 4, true, 1),
('Cloud / DevOps', 'Infrastructure as Code Failure', 12, true, 1),
('Cloud / DevOps', 'Kubernetes Pod Failure', 4, true, 1),
('Cloud / DevOps', 'Log Ingestion Failure', 8, true, 1),
('Cloud / DevOps', 'Monitoring Alert Noise', 24, true, 1),
('Cloud / DevOps', 'Resource Quota Exhausted', 6, true, 1),
('Cloud / DevOps', 'Secrets Exposure', 2, true, 1),
('Cloud / DevOps', 'Other Cloud / DevOps Issue', 24, true, 1),

-- Compliance (ID 3)
('Compliance', 'Access Review Failure', 24, true, 3),
('Compliance', 'Audit Non-Compliance', 24, true, 3),
('Compliance', 'Compliance Reporting Delay', 48, true, 3),
('Compliance', 'Data Retention Violation', 24, true, 3),
('Compliance', 'Internal Control Failure', 24, true, 3),
('Compliance', 'ISO Compliance Gap', 48, true, 3),
('Compliance', 'Legal Hold Violation', 12, true, 3),
('Compliance', 'Missing Documentation', 48, true, 3),
('Compliance', 'Policy Review Delay', 72, true, 3),
('Compliance', 'Privacy Impact Risk', 12, true, 3),
('Compliance', 'Regulatory Violation', 12, true, 3),
('Compliance', 'Risk Assessment Overdue', 72, true, 3),
('Compliance', 'SLA Breach Detected', 1, true, 3),
('Compliance', 'SOX Control Failure', 24, true, 3),
('Compliance', 'Vendor Compliance Issue', 48, true, 3),
('Compliance', 'Other Compliance Issue', 24, true, 3),

-- Data & Analytics (ID 1)
('Data & Analytics', 'Analytics Dashboard Failure', 8, true, 1),
('Data & Analytics', 'Data Access Denied', 4, true, 1),
('Data & Analytics', 'Data Drift Detected', 24, true, 1),
('Data & Analytics', 'Data Pipeline Failure', 6, true, 1),
('Data & Analytics', 'Data Privacy Risk', 6, true, 1),
('Data & Analytics', 'Data Quality Issue', 12, true, 1),
('Data & Analytics', 'ETL Job Failure', 8, true, 1),
('Data & Analytics', 'Feature Store Inconsistency', 12, true, 1),
('Data & Analytics', 'Model Performance Degradation', 24, true, 1),
('Data & Analytics', 'Reporting Delay', 24, true, 1),
('Data & Analytics', 'Other Data / Analytics Issue', 24, true, 1),

-- Finance (ID 6)
('Finance', 'Billing Discrepancy', 24, true, 6),
('Finance', 'Budget Overrun Alert', 24, true, 6),
('Finance', 'Cost Allocation Error', 24, true, 6),
('Finance', 'Expense Reimbursement Delay', 72, true, 6),
('Finance', 'Financial Approval Delay', 48, true, 6),
('Finance', 'Invoice Processing Delay', 48, true, 6),
('Finance', 'Payment Failure', 24, true, 6),
('Finance', 'Revenue Leakage Identified', 12, true, 6),
('Finance', 'Tax Deduction Error', 48, true, 6),
('Finance', 'Vendor Payment Delay', 48, true, 6),
('Finance', 'Other Finance Issue', 48, true, 6),

-- HR / Policy (ID 5)
('HR / Policy', 'Attendance Policy Violation', 72, true, 5),
('HR / Policy', 'Background Verification Delay', 48, true, 5),
('HR / Policy', 'Code of Conduct Violation', 48, true, 5),
('HR / Policy', 'Compensation Dispute', 48, true, 5),
('HR / Policy', 'Conflict of Interest Issue', 48, true, 5),
('HR / Policy', 'Employee Grievance', 72, true, 5),
('HR / Policy', 'Exit Process Delay', 48, true, 5),
('HR / Policy', 'Harassment Complaint', 24, true, 5),
('HR / Policy', 'Leave Policy Dispute', 72, true, 5),
('HR / Policy', 'Onboarding Delay', 48, true, 5),
('HR / Policy', 'Payroll Discrepancy', 24, true, 5),
('HR / Policy', 'Policy Acknowledgement Missing', 72, true, 5),
('HR / Policy', 'Training Compliance Missed', 72, true, 5),
('HR / Policy', 'Unauthorized Absence', 72, true, 5),
('HR / Policy', 'Workplace Misconduct', 48, true, 5),
('HR / Policy', 'Other HR Issue', 48, true, 5),

-- Infrastructure (ID 4)
('Infrastructure', 'AC Cooling Issue', 12, true, 4),
('Infrastructure', 'AC Not Working', 8, true, 4),
('Infrastructure', 'AC Water Leakage', 6, true, 4),
('Infrastructure', 'Access Card Not Working', 6, true, 4),
('Infrastructure', 'CCTV Malfunction', 24, true, 4),
('Infrastructure', 'Desk or Chair Broken', 24, true, 4),
('Infrastructure', 'Drinking Water Facility Issue', 12, true, 4),
('Infrastructure', 'Emergency Lighting Failure', 6, true, 4),
('Infrastructure', 'Fire Safety Issue', 1, true, 4),
('Infrastructure', 'Lighting Failure', 8, true, 4),
('Infrastructure', 'Meeting Room AV Failure', 8, true, 4),
('Infrastructure', 'Network Cabling Damage', 12, true, 4),
('Infrastructure', 'Office Internet Outage', 4, true, 4),
('Infrastructure', 'Pantry Equipment Failure', 24, true, 4),
('Infrastructure', 'Physical Access Control Failure', 6, true, 4),
('Infrastructure', 'Power Failure', 2, true, 4),
('Infrastructure', 'UPS Failure', 2, true, 4),
('Infrastructure', 'Washroom Maintenance Issue', 12, true, 4),
('Infrastructure', 'Water Leakage', 12, true, 4),
('Infrastructure', 'Workstation Power Socket Issue', 8, true, 4),
('Infrastructure', 'Other Infrastructure Issue', 24, true, 4),

-- IT / Technical (ID 1)
('IT / Technical', 'Application Crash', 6, true, 1),
('IT / Technical', 'Application Performance Degradation', 8, true, 1),
('IT / Technical', 'Backup Failure', 24, true, 1),
('IT / Technical', 'Database Outage', 2, true, 1),
('IT / Technical', 'Database Performance Issue', 6, true, 1),
('IT / Technical', 'Driver Compatibility Issue', 24, true, 1),
('IT / Technical', 'Email Service Failure', 8, true, 1),
('IT / Technical', 'File Server Inaccessible', 12, true, 1),
('IT / Technical', 'Network Connectivity Failure', 4, true, 1),
('IT / Technical', 'OS Corruption', 12, true, 1),
('IT / Technical', 'Patch Deployment Failure', 24, true, 1),
('IT / Technical', 'Printer Service Failure', 48, true, 1),
('IT / Technical', 'Restore Failure', 12, true, 1),
('IT / Technical', 'Server Down', 2, true, 1),
('IT / Technical', 'VPN Access Failure', 6, true, 1),
('IT / Technical', 'Other IT Issue', 24, true, 1),

-- Operations (ID 7)
('Operations', 'Approval Delay', 24, true, 7),
('Operations', 'Automation Job Failure', 12, true, 7),
('Operations', 'Batch Processing Failure', 8, true, 7),
('Operations', 'Change Management Failure', 16, true, 7),
('Operations', 'Data Processing Delay', 16, true, 7),
('Operations', 'Dependency Failure', 12, true, 7),
('Operations', 'Manual Intervention Required', 12, true, 7),
('Operations', 'Operational Escalation Required', 4, true, 7),
('Operations', 'Operational Policy Deviation', 48, true, 7),
('Operations', 'Process Documentation Missing', 48, true, 7),
('Operations', 'Process Failure', 8, true, 7),
('Operations', 'Release Management Issue', 12, true, 7),
('Operations', 'Resource Unavailability', 24, true, 7),
('Operations', 'Scheduling Failure', 24, true, 7),
('Operations', 'Workflow Breakdown', 12, true, 7),
('Operations', 'Other Operations Issue', 24, true, 7),

-- Security (ID 2)
('Security', 'Antivirus Outdated', 24, true, 2),
('Security', 'Brute Force Login Attempt', 4, true, 2),
('Security', 'Data Breach', 1, true, 2),
('Security', 'Data Leakage Risk', 2, true, 2),
('Security', 'Endpoint Security Alert', 6, true, 2),
('Security', 'Firewall Misconfiguration', 12, true, 2),
('Security', 'Malware Infection', 6, true, 2),
('Security', 'Password Compromise', 8, true, 2),
('Security', 'Phishing Attack', 4, true, 2),
('Security', 'Privilege Escalation Attempt', 2, true, 2),
('Security', 'Ransomware Attack', 1, true, 2),
('Security', 'Security Patch Missing', 24, true, 2),
('Security', 'Suspicious Login Activity', 4, true, 2),
('Security', 'Unauthorized System Access', 2, true, 2),
('Security', 'USB Policy Violation', 24, true, 2),
('Security', 'Other Security Issue', 12, true, 2),

-- Vendor (ID 8)
('Vendor', 'Contractual Obligation Missed', 24, true, 8),
('Vendor', 'Dependency Risk Escalation', 12, true, 8),
('Vendor', 'License Expiry Risk', 24, true, 8),
('Vendor', 'Third Party SLA Breach', 12, true, 8),
('Vendor', 'Vendor Invoice Dispute', 48, true, 8),
('Vendor', 'Vendor Offboarding Issue', 48, true, 8),
('Vendor', 'Vendor Onboarding Delay', 72, true, 8),
('Vendor', 'Vendor Performance Issue', 48, true, 8),
('Vendor', 'Vendor Security Risk', 4, true, 8),
('Vendor', 'Vendor Service Downtime', 24, true, 8),
('Vendor', 'Other Vendor Issue', 48, true, 8),

-- Other / Unclassified (ID 9)
('Other / Unclassified', 'Not Listed', 24, true, 9);