package com.incidenttracker.backend.task.entity;

import java.time.LocalDateTime;

import com.incidenttracker.backend.common.enums.TaskStatus;
import com.incidenttracker.backend.incident.entity.Incident;
import com.incidenttracker.backend.user.entity.User;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "tasks")
@NoArgsConstructor
@AllArgsConstructor
@Builder
@Getter
@Setter
public class Task {

    // Primary key generated by database identity strategy.
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long taskId;

    // Short summary used in task listings.
    @Column(name = "title")
    private String title;

    // Detailed task instructions/context.
    @Column(name = "description")
    private String description;

    // Expected completion deadline, typically aligned with incident SLA.
    @Column(name = "due_date", nullable = false)
    private LocalDateTime dueDate;

    // Current workflow state of the task.
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private TaskStatus status;

    // Timestamp when task was created.
    @Column(name = "created_date", nullable = false)
    private LocalDateTime createdDate;

    // Timestamp set when task is marked completed.
    @Column(name = "completed_date")
    private LocalDateTime completedDate;

    // Incident this task belongs to.
    @ManyToOne(fetch = FetchType.LAZY, optional = false) // Foreign Key
    @JoinColumn(name = "incident_id", nullable = false)
    Incident incident;

    // Employee/user the task is assigned to.
    @ManyToOne(fetch = FetchType.LAZY, optional = false) // Foreign Key
    @JoinColumn(name = "assigned_to", nullable = false)
    User assignedTo;

    // User (typically manager) who assigned the task.
    @ManyToOne(fetch = FetchType.LAZY, optional = false) // Foreign Key
    @JoinColumn(name = "assigned_by", nullable = false)
    User assignedBy;

    // Initializes default task timestamps and workflow state.
    @PrePersist
    void onCreate() {
        createdDate = LocalDateTime.now();
        if (status == null) {
            status = TaskStatus.PENDING;
        }
    }

}
